//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecurePad.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecurePad.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SecurePad.
        /// </summary>
        public static string APP_NAME {
            get {
                return ResourceManager.GetString("APP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication failed!.
        /// </summary>
        public static string AUTH_FAILED {
            get {
                return ResourceManager.GetString("AUTH_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticate access to notepad..
        /// </summary>
        public static string AUTH_MSG {
            get {
                return ResourceManager.GetString("AUTH_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication succeeded!.
        /// </summary>
        public static string AUTH_SUCCESS {
            get {
                return ResourceManager.GetString("AUTH_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biometric authentication is not available..
        /// </summary>
        public static string BIO_OFF {
            get {
                return ResourceManager.GetString("BIO_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use fingerprint.
        /// </summary>
        public static string BUTTON_BIOMETRICS {
            get {
                return ResourceManager.GetString("BUTTON_BIOMETRICS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string BUTTON_CANCEL {
            get {
                return ResourceManager.GetString("BUTTON_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string BUTTON_DELETE {
            get {
                return ResourceManager.GetString("BUTTON_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        public static string BUTTON_ENTER {
            get {
                return ResourceManager.GetString("BUTTON_ENTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string BUTTON_SAVE {
            get {
                return ResourceManager.GetString("BUTTON_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string CHNG_PASSWD_TTLE {
            get {
                return ResourceManager.GetString("CHNG_PASSWD_TTLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created encryption key..
        /// </summary>
        public static string ENC_KEY_CREATED {
            get {
                return ResourceManager.GetString("ENC_KEY_CREATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text:.
        /// </summary>
        public static string ITEM_CONTENT_LABEL {
            get {
                return ResourceManager.GetString("ITEM_CONTENT_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title:.
        /// </summary>
        public static string ITEM_TITLE_LABEL {
            get {
                return ResourceManager.GetString("ITEM_TITLE_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new password:.
        /// </summary>
        public static string NEW_PASSWD_LABEL {
            get {
                return ResourceManager.GetString("NEW_PASSWD_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string NOTE_DETAIL_TITLE {
            get {
                return ResourceManager.GetString("NOTE_DETAIL_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string NOTE_EDIT_TITLE {
            get {
                return ResourceManager.GetString("NOTE_EDIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New note.
        /// </summary>
        public static string NOTE_NEW_TITLE {
            get {
                return ResourceManager.GetString("NOTE_NEW_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string NOTES_TITLE {
            get {
                return ResourceManager.GetString("NOTES_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password changed!.
        /// </summary>
        public static string PASSWD_CHNG_TOAST {
            get {
                return ResourceManager.GetString("PASSWD_CHNG_TOAST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You did not provide any password..
        /// </summary>
        public static string PASSWD_EMPTY {
            get {
                return ResourceManager.GetString("PASSWD_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string PASSWD_LABEL {
            get {
                return ResourceManager.GetString("PASSWD_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter password.
        /// </summary>
        public static string PASSWD_TITLE {
            get {
                return ResourceManager.GetString("PASSWD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password has not been set yet. Use biometrics..
        /// </summary>
        public static string PASSWD_UNSET {
            get {
                return ResourceManager.GetString("PASSWD_UNSET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must have at least {0} character(s), at least {1} in upper case, {2} in lower and {3} digit(s)..
        /// </summary>
        public static string PASSWD_WEAK_TOAST {
            get {
                return ResourceManager.GetString("PASSWD_WEAK_TOAST", resourceCulture);
            }
        }
    }
}
